### ISSUE TITLE
Implementing Basic Levelgenerator Prototype

### ISSUE THREAD

**Issue by Osmil** [HTWGameDevelopment/2017WS_More_Options#1]
Description / 1.11.2017

**Comment by AndreasBonny** [comment]
The levelgenerator implementation creates a randomly generated minimap with differen kinds of rooms.
The amount of rooms is variable so that the number can be higher at later stages of the game. 

It does so by first generation a starting room in which the player will be placed upon start of each level. Next it will generate "normal" rooms which the player has to go through in order to reach the next level. Once the maximal number of normal rooms is reached, special rooms will be added (boss room, item room, vendor and a secret room). The amount of special rooms might change in the future. Those special rooms can only have one neigbour so that it is guaranteed that the player can reach every room. An exception is the secret room which has multiple neighbours.

**Comment by Osmil** [comment]
Basic Levelgenerator implemented. [1f95634]
